#pull the httpd docker image from docker hub
FROM httpd:latest

# person who is maintaining the dockr file
MAINTAINER "vgold999@gmail.com"

# copying the fitness application files from the source directory to destination HTTPD container directory
COPY ./C:\Users\Varun\Downloads\Energym Free Website Template - Free-CSS.com\energym-html./project/ */usr/local/apache2/htdocs/
